/**
 * name : common.js
 * author : Aman
 * created-date : 31-May-2020
 * Description : Common message.
 */

 module.exports = {
  ASSESSMENT : "assessment",
  OBSERVATION : "observation",
  INSTITUTIONAL :"institutional",
  INDIVIDUAL : "individual",
  ENTITIES : "entities",
  OBSERVATION_METAFORM : "defaultObservationMetaForm",
  ASSESSMENT_META_FORM_KEY : "assessmentMetaFormKey",
  INSTITUTIONAL_METAFORM : "defaultInstitutionalMetaForm",
  INDIVIDUAL_METAFORM : "defaultIndividualMetaForm",
  PUBLISHED : "published",
  ACTIVE_STATUS : "active",
  INACTIVE_STATUS : "inactive",
  STARTED : "started",
  LEAD_ASSESSOR : "LEAD_ASSESSOR",
  MANUAL_RATING : "manual",
  POINTS_BASED_SCORING_SYSTEM : "pointsBasedScoring",
  AUTO_RATING : "auto",
  SUBMISSION_STATUS_RATING_PENDING: "ratingPending",
  SUBMISSION_STATUS_COMPLETED : "completed",
  SUBMISSION_STATUS_STARTED : "started",
  SUBMISSION_STATUS_NOT_STARTED : "notstarted",
  IMAGE_FORMATS : ["png","jpg","jpeg","svg"],
  VIDEO_FORMATS : ["webm","mpg","mp2","mpeg", "mpe","mpv","ogg","mp4","m4p","m4v","avi","wmv"],
  DOCUMENT_FORMATS : ["txt","csv","pdf","doc","docx","odt","ppt","pptx","html","rtf","htm","xls","xlsx","xla"],
  POLL_METAFORM : "defaultPollCreationForm",
  POLL_QUESTION_METAFORM : "defaultPollQuestionForm",
  EMOJI : "emoji",
  GESTURE : "gesture",
  TAKE_POLL : "/take-poll/",
  CREATE_OBSERVATION : "/create-observation/",
  SURVEY : "survey",
  TAKE_SURVEY : "/take-survey/",
  EXPIRED: "expired",
  SURVEY_SUBMISSIONS: "surveySubmissions",
  OBSERVATION_SUBMISSIONS: "observationSubmissions",
  SUBMISSIONS: "submissions",
  VERSION_1 : "v1",
  VERSION_2 : "v2",
  PROJECT : "project",
  IMPROVEMENT_PROJECT : "improvementProject",
  SCHOOL : "school",
  DEFAULT_PAGE_NO : 1,
  DEFAULT_PAGE_SIZE : 100,
  SUCCESS : "success",
  ASSIGN_TO_ME : "assignedToMe",
  CREATED_BY_ME : "createdByMe",
  ALL_ROLES : "all",
  VERSION_3 : "v3",
  DRAFT : "draft",
  DISTRICT : "district",
  SERVER_TIME_OUT : 5000,
  OK : "OK",
  PROFILE_CONFIG_FORM_KEY : "profileConfig_v2",
  CACHE_TTL : 43200 ,
  GET_METHOD : "GET",
  SUBENTITY :"subEntityTypesOf_",
  STATE: "state",
  TELEMETRY_VERSION: "3.0",
  DELETED_USER: "Deleted User",
  TELEMTRY_EVENT_LOGGER: "TelemetryEventLogger",
  INFO_LEVEL: "INFO",
  DELETE_STATE: "Delete",
  USER_DELETE_TYPE: "DeleteUserStatus",
  AUDIT: "AUDIT",
  DELETE_USER: "delete-user",
  USER: "User",
  USER_DELETE_MODULE: "userDelete",
  OFF: "OFF"

}